services:
  php:
    build:
      context: .
      dockerfile: .devcontainer/docker/php/Dockerfile
    command: ["sleep", "infinity"]
    volumes:
      - .:/workspaces/inventory-management-system
  mysql:
    build:
      context: .
      dockerfile: .devcontainer/docker/database/mysql/Dockerfile

  phpmyadmin:
    image: phpmyadmin:latest

